import React from 'react';
import { useTestStore } from '../../store/testStore';
import { useAuthStore } from '../../store/authStore';
import { storageService } from '../../services/storage/storageService';
import { useToastStore } from '../../store/toastStore';
import { generateTestCertificatePDF } from '../../services/reports/pdfService';
import { Button } from '../../components/common/Button';
import {
  Download,
  Printer,
  FileText,
  Award,
  ShieldCheck,
  CheckCircle2,
} from 'lucide-react';
import {
  formatCurrent,
  formatVoltage,
  formatJouleIntegral,
  formatTimeMs,
  formatDate,
} from '../../utils/formatters';

export const TestReportPage: React.FC = () => {
  const {
    mcb,
    configuration,
    rlConfig,
    cvuVerification,
    calibration,
    activeResult,
    activeWaveform,
    savedRecordId,
  } = useTestStore();
  const { currentOperator } = useAuthStore();
  const toast = useToastStore();
  const tests = storageService.getTests();

  // Active record to preview
  const currentRecord: import('../../types').TestRecord = {
    id: savedRecordId || tests[0]?.id || `TEST-${Date.now()}`,
    createdAt: new Date().toISOString(),
    operator: currentOperator || {
      id: 'OP-4829',
      name: 'Er. Sharma',
      badgeNumber: 'STN4-ENG-4829',
      role: 'ADMIN',
      labStation: 'Station 02 - High-Current Rig',
    },
    mcb,
    configuration,
    rlConfig,
    cvuVerification,
    calibration,
    waveform: activeWaveform || tests[0]?.waveform,
    result: activeResult || tests[0]?.result,
    status: activeResult?.overallResult === 'PASS' ? 'COMPLETED' : 'FAILED',
  };

  const isPass = currentRecord.result?.overallResult === 'PASS';

  const handleDownloadPDF = () => {
    generateTestCertificatePDF(currentRecord, true);
    toast.success('Certificate Downloaded', `Generated official PDF for ${currentRecord.id}`);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-4 max-w-5xl mx-auto">
      {/* Top Action Bar (hidden in print) */}
      <div className="bg-white border border-slate-200 rounded-md p-4 shadow-2xs flex flex-wrap items-center justify-between gap-4 no-print">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-slate-900 tracking-tight">
              IEC 60898-1 Test Certificate Report
            </h1>
            <span
              className={`px-2 py-0.5 rounded text-[11px] font-mono font-bold ${
                isPass ? 'bg-emerald-50 text-emerald-800 border border-emerald-300' : 'bg-red-50 text-red-800 border border-red-300'
              }`}
            >
              {isPass ? 'COMPLIANT (PASS)' : 'NON-COMPLIANT (FAIL)'}
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Official metrological laboratory certificate generated by the automated MCB short-circuit testing station.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            size="sm"
            variant="primary"
            onClick={handleDownloadPDF}
            leftIcon={<Download className="w-3.5 h-3.5" />}
          >
            Download Official PDF
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={handlePrint}
            leftIcon={<Printer className="w-3.5 h-3.5" />}
          >
            Print Certificate
          </Button>
        </div>
      </div>

      {/* CERTIFICATE PREVIEW CONTAINER */}
      <div className="bg-white border border-slate-300 rounded-md shadow-xs p-6 md:p-8 font-sans print:border-none print:shadow-none print:p-0">
        {/* Certificate Header Banner */}
        <div className="border-b-2 border-slate-900 pb-4 mb-5 flex items-start justify-between">
          <div>
            <span className="text-[10px] font-mono uppercase tracking-widest text-teal-700 font-bold block">
              ACCREDITED SHORT-CIRCUIT LABORATORY • ISO/IEC 17025
            </span>
            <h2 className="text-xl font-bold text-slate-900 uppercase font-mono mt-1">
              AUTOMATED MCB TEST BENCH CERTIFICATE
            </h2>
            <p className="text-xs text-slate-600 mt-0.5">
              Standard: <strong>IEC 60898-1:2015</strong> (Circuit-breakers for overcurrent protection for household and similar installations)
            </p>
          </div>

          <div className="text-right">
            <div className="text-xs font-mono font-bold text-slate-900">
              REF: {currentRecord.id}
            </div>
            <div className="text-[11px] text-slate-500 font-mono mt-0.5">
              DATE: {formatDate(currentRecord.createdAt)}
            </div>
            <div className="mt-2">
              <span
                className={`px-2.5 py-0.5 rounded font-mono text-xs font-bold ${
                  isPass ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'
                }`}
              >
                VERDICT: {isPass ? 'PASS' : 'FAIL'}
              </span>
            </div>
          </div>
        </div>

        {/* Section 1: Specimen Identification */}
        <div className="mb-5">
          <div className="bg-slate-100 px-3 py-1.5 rounded text-xs font-bold text-slate-800 uppercase tracking-wider mb-2.5 font-mono">
            1. Test Specimen Identification (Device Under Test)
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-y-2 text-xs">
            <div>
              <span className="text-slate-500 block">Manufacturer:</span>
              <strong className="text-slate-900">{currentRecord.mcb.manufacturer}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Model / Catalog No:</span>
              <strong className="text-slate-900 font-mono">{currentRecord.mcb.modelNumber}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Serial Number:</span>
              <strong className="text-slate-900 font-mono">{currentRecord.mcb.serialNumber || 'N/A'}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Pole Configuration:</span>
              <strong className="text-slate-900 font-mono">{currentRecord.mcb.poles}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Rated Current (In):</span>
              <strong className="text-slate-900 font-mono">{currentRecord.mcb.ratedCurrentA} A</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Tripping Characteristic:</span>
              <strong className="text-slate-900 font-mono">
                Curve {currentRecord.mcb.trippingCurve} ({currentRecord.mcb.instantaneousTrippingRange})
              </strong>
            </div>
          </div>
        </div>

        {/* Section 2: Prospective Test Parameters */}
        <div className="mb-5">
          <div className="bg-slate-100 px-3 py-1.5 rounded text-xs font-bold text-slate-800 uppercase tracking-wider mb-2.5 font-mono">
            2. Prospective Circuit Conditions & Switched R-L Matrix
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-y-2 text-xs">
            <div>
              <span className="text-slate-500 block">Prospective Current (Icn):</span>
              <strong className="text-slate-900 font-mono">
                {formatCurrent(currentRecord.configuration.prospectiveCurrentA)}
              </strong>
            </div>
            <div>
              <span className="text-slate-500 block">Target Power Factor:</span>
              <strong className="text-slate-900 font-mono">
                {currentRecord.configuration.targetPowerFactor} (cos φ)
              </strong>
            </div>
            <div>
              <span className="text-slate-500 block">System Voltage & Freq:</span>
              <strong className="text-slate-900 font-mono">
                {currentRecord.configuration.systemVoltageV} V / {currentRecord.configuration.systemFrequencyHz} Hz
              </strong>
            </div>
            <div>
              <span className="text-slate-500 block">Test Duty Cycle:</span>
              <strong className="text-slate-900 font-mono">{currentRecord.configuration.shotCycle}</strong>
            </div>
            <div>
              <span className="text-slate-500 block">Closing Point-on-Wave:</span>
              <strong className="text-slate-900 font-mono">
                {currentRecord.configuration.breakArcInceptionAngleDeg}°
              </strong>
            </div>
            <div>
              <span className="text-slate-500 block">Circuit Impedance (Z):</span>
              <strong className="text-slate-900 font-mono">
                {currentRecord.rlConfig?.actualResistanceOhms} Ω + j{currentRecord.rlConfig?.actualReactanceOhms} Ω
              </strong>
            </div>
          </div>
        </div>

        {/* Section 3: Measured Performance Parameters Table */}
        <div className="mb-5">
          <div className="bg-slate-100 px-3 py-1.5 rounded text-xs font-bold text-slate-800 uppercase tracking-wider mb-2.5 font-mono">
            3. Measured Telemetry & IEC 60898-1 Limiting Criteria Audit
          </div>
          <table className="w-full text-left text-xs border border-slate-200">
            <thead className="bg-slate-50 border-b border-slate-200 text-slate-600 font-semibold font-mono text-[10px] uppercase">
              <tr>
                <th className="py-2 px-3">Parameter Evaluated</th>
                <th className="py-2 px-3">Measured Telemetry</th>
                <th className="py-2 px-3">Standard Limit Band</th>
                <th className="py-2 px-3">Clause Reference</th>
                <th className="py-2 px-3 text-right">Result</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-mono">
              {currentRecord.result?.criteria?.map((c, idx) => (
                <tr key={idx}>
                  <td className="py-2 px-3 font-sans font-medium text-slate-900">{c.parameter}</td>
                  <td className="py-2 px-3 font-bold text-slate-900">
                    {c.parameter.includes('Current')
                      ? formatCurrent(c.measured)
                      : c.parameter.includes('Integral')
                      ? formatJouleIntegral(c.measured)
                      : c.parameter.includes('Time') || c.parameter.includes('Duration')
                      ? formatTimeMs(c.measured)
                      : c.parameter.includes('Voltage')
                      ? formatVoltage(c.measured)
                      : c.measured.toFixed(3)}
                  </td>
                  <td className="py-2 px-3 text-slate-600">
                    {c.limitMax ? `Max ${c.limitMax} ${c.unit}` : c.limitMin ? `Min ${c.limitMin} ${c.unit}` : '-'}
                  </td>
                  <td className="py-2 px-3 font-sans text-slate-500">{c.standardReference}</td>
                  <td className="py-2 px-3 text-right font-sans">
                    <span className={c.pass ? 'text-emerald-700 font-bold' : 'text-red-700 font-bold'}>
                      {c.pass ? 'PASS' : 'FAIL'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Section 4: Certification Statement Box */}
        <div
          className={`p-3.5 rounded-md border mb-5 text-xs ${
            isPass ? 'bg-emerald-50/70 border-emerald-300 text-emerald-950' : 'bg-red-50/70 border-red-300 text-red-950'
          }`}
        >
          <strong className="block mb-1 text-xs font-bold font-mono">OFFICIAL EVALUATION VERDICT:</strong>
          <p className="leading-relaxed">
            {currentRecord.result?.complianceVerdict ||
              'Evaluation performed in accordance with IEC 60898-1:2015 Clause 9.12.'}
          </p>
        </div>

        {/* Section 5: Metrology & Signatures */}
        <div className="grid grid-cols-2 gap-8 pt-3 border-t border-slate-200 text-xs">
          <div>
            <span className="text-slate-500 block mb-1">Testing Laboratory Signatory:</span>
            <div className="font-bold text-slate-900">{currentRecord.operator.name}</div>
            <div className="text-[11px] text-slate-500 font-mono">Lead Metrology Engineer ({currentRecord.operator.badgeNumber})</div>
            <div className="mt-3 border-t border-dashed border-slate-300 pt-1 text-[10px] text-slate-400 font-mono">
              Verified Electronic Signature Seal
            </div>
          </div>
          <div className="text-right">
            <span className="text-slate-500 block mb-1">Calibration Traceability:</span>
            <div className="font-bold text-slate-900 font-mono">{currentRecord.calibration.referenceMeterModel}</div>
            <div className="text-[11px] text-slate-500 font-mono">Cert: {currentRecord.calibration.certificateId}</div>
            <div className="mt-3 border-t border-dashed border-slate-300 pt-1 text-[10px] text-slate-400 font-mono">
              Standard: IEC 60898-1:2015 / ISO/IEC 17025
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
